### ISSUE TITLE
Issues with raspberry pi zero

### ISSUE THREAD

**Issue by koosthoe** [nopnop2002/ili9225spi_rpi#2]
demo.c: In function ‘main’:
demo.c:38:3: warning: implicit declaration of function ‘Fontx_init’ [-Wimplicit-function-declaration]
   Fontx_init(fxG16,"./fontx/ILGH16XB.FNT","./fontx/ILGZ16XB.FNT");
   ^~~~~~~~~~
demo.c:263:3: warning: implicit declaration of function ‘srand’ [-Wimplicit-function-declaration]
   srand( (unsigned int)time( NULL ) );
   ^~~~~
demo.c:263:24: warning: implicit declaration of function ‘time’ [-Wimplicit-function-declaration]
   srand( (unsigned int)time( NULL ) );
                        ^~~~
demo.c:265:9: warning: implicit declaration of function ‘rand’ [-Wimplicit-function-declaration]
     red=rand()%255;
         ^~~~
ili9225.c: In function ‘lcdDrawSJISChar’:
ili9225.c:557:12: warning: ‘return’ with no value, in function returning non-void
   if (!rc) return;
            ^~~~~~
ili9225.c:543:5: note: declared here
 int lcdDrawSJISChar(FontxFile *fx, uint16_t x,uint16_t y,uint16_t sjis,uint16_t color) {
     ^~~~~~~~~~~~~~~

______________________________________________________________
This is the error i get when trying the bcm2835 library and the wiringPi library

**Comment by danasourasrex** [comment]
I'm also getting similar errors. Did you get it to work?

**Comment by nopnop2002** [comment]
Download latest and 

cc -o demo demo.c fontx.c ili9225.c -lbcm2835 -lm -lpthread

cc -o demo demo.c fontx.c ili9225.c -lwiringPi -lm -lpthread -DWPI
